### PR TITLE
BEAR-70: Default paragraph bundles.

### PR DESCRIPTION
**Pull request by jkaeser**
https://jira.zivtech.com/browse/BEAR-70

### CODE REVIEW

**Comment by jodyHamilton** [comment]
yay

**Comment by tortillaj** [comment]
yayay

**Comment by jkaeser** [comment]
## To test:

1. Log in as admin.
2. Create a paragraph reference field on the basic page node type that allows references to all paragraph types. Currently there should be none available.
3. Begin enabling the bear paragraph modules.
   * Each should only require the Paragraphs module, not each other or any other module.
4. Test each module according to their function. See the ticket and its subtasks for more information: https://jira.zivtech.com/browse/BEAR-70. Each subtask does (or will soon) include acceptance criteria to test against.

**Comment by tortillaj** [comment]
charlie
itshappening
lightning

**Review by tortillaj — APPROVED** [review]
ship it

**Pull request merged**
