### PR TITLE
Create Homepage.feature

### PR DESCRIPTION
**Pull request by julesrocks**

### CODE REVIEW

**Comment by sk33lz** [comment]
Thanks for attending the training!

**Comment by julesrocks** [comment]
I enjoyed it.  I have additional questions regarding setting up the virtual servers.  How can I reach you?

Julie F. Hall

Custom Websites to Go

214-417-8682

www.csites2go.com

**Comment by julesrocks** [comment]
Getting error message vcsrepo does not exist.  Something went wrong.  Try removing it manually.  Librarian::Error

**Pull request closed without merging**
