### PR TITLE
Swapping out wysiwyg+media in favor of ckeditor+asset

### PR DESCRIPTION
**Pull request by grndlvl**
- Removed wysiwyg, file_entity, and media modules
- Added asset, ckeditor, and jplayer
- Added Ckeditor settings per Jason's suggestions
- Configured asset to have video, ~~audio~~, document, and image
- Added video, ~~audio~~, document, image, and search
- Added the asset widget
- Removed all media+wysiwyg permissions from profile
- Added asset permissions to profile

I notice the Travis build is failing, but it doesn't seem like it was setup. So I am not sure if these tests are still valid. I imagine we'd need to update them since we changed some of the core functionality of the WYSIWYG editor.

I also imagine we'd want to create a new branch and not actually merge this into 7.x-1.x.

### CODE REVIEW

**Comment by jodyHamilton** [comment]
This is the build https://fca0b4b0-557f-463d-8d55-9513ebe432e9.probo.build
and the probo info https://app.probo.ci/#/dashboard/build/fca0b4b0-557f-463d-8d55-9513ebe432e9

Somehow media still got added and asset didnt get enabled. Can you look through the build steps and output and try to figure out?

If you click on 'install bear' task you'll find the password

**Comment by grndlvl** [comment]
Probo isn't pulling the right branch when building -- it's using the contents of build-bear.make which points to 7.x-1.x instead of the branch to be used for testing. I have adjusted to use this branch when building. Will need to revert d92765e8a4f10e86e46c935488e770f1a2ffca65 before merging.

**Comment by grndlvl** [comment]
- Adding oembed configurations
- Adding embed asset entity and associated fields
- Adding work around for semantic-ui breakage on the node/add page
- Adding patch for custom icons for asset elements
- Adding css for embed icon for the asset_widget
- Creating bear_skin template to remove titles from assets

**Comment by jhoscar1** [comment]
Added the asset video patch https://www.drupal.org/node/2174613#comment-10425469 to the patches.make and drupal-org.make

**Comment by grndlvl** [comment]
@jhoscar1 Why did we patch the asset_youtube module? We aren't using it here.

**Comment by jhoscar1** [comment]
@grndlvl I guess I named the patch poorly. It's a patch to asset to enable youtube videos to be properly rendered on Firefox and Chrome. I was having an issue on a site where Firefox wouldn't render youtube videos in the default video asset. Jody asked me to put the patch on bear.

**Pull request merged**
